# Generated by Django 4.1.1 on 2023-02-09 17:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_checkout'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Checkout',
        ),
    ]
