# Generated by Django 4.1.1 on 2023-02-03 09:28

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(help_text='Contact phone number', max_length=128, region=None),
        ),
    ]
