# Generated by Django 4.1.1 on 2023-01-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_category_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='addition',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
